<?php
/**
 * @file
 * µSync developer UI module.
 */

use USync\AST\Drupal\DrupalNodeInterface;
use USync\Context;

/**
 * Implements hook_menu().
 */
function usync_ui_menu() {
  $items = [];

  $items['admin/structure/usync'] = [
    'title'             => 'µSync',
    'page callback'     => 'usync_ui_tree',
    'access arguments'  => ['yes I am a developer'],
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'usync_ui.tree.inc',
  ];
  $items['admin/structure/usync/pane'] = [
    'title'             => "Component information",
    'page callback'     => 'usync_ui_pane',
    'access arguments'  => ['yes I am a developer'],
    'type'              => MENU_CALLBACK,
    'file'              => 'usync_ui.tree.inc',
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function usync_ui_theme() {
  return [
    'usync_ui_tree' => [
      'variables' => ['tree' => null],
      'template' => 'usync-ui-tree',
    ],
    'usync_ui_info_pane' => [
      'variables' => ['graph' => null, 'node' => null, 'form' => null, 'more' => null, 'loaders' => []],
      'template' => 'usync-ui-info-pane',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_usync_ui_info_pane(&$variables) {

  $node = $variables['node'];

  $variables['context'] = $context = new Context();

  $status = t("N/A");
  $type   = 'info';

  if ($node instanceof DrupalNodeInterface) {
    if ($variables['loaders']) {

      $total  = count($variables['loaders']);
      $actual = 0;

      /* @var $loader \USync\Loading\LoaderInterface */
      foreach ($variables['loaders'] as $loader) {
        if ($loader->exists($node, $context)) {
          ++$actual;
        }
      }

      if ($node->shouldDelete()) {
        if (!$actual) {
          $status = t("Deleted");
          $type   = 'success';
        } else {
          $status = t("To be deleted");
          $type   = 'danger';
        }
      } else {
        if (!$actual) {
          $status = t("To be inserted");
          $type   = 'danger';
        } else if ($total !== $actual ) {
          $status = t("Partially inserted");
          $type   = 'warning';
        } else {
          $status = t("Merged");
          $type   = 'success';
        }
      }
    }
  }

  $variables['status'] = [
    '#prefix' => '<span class="text-' . $type . '">',
    '#markup' => $status,
    '#suffix' => '</span>',
  ];
}
